version: 1.0.{build}
skip_tags: true

environment:
  PYTHON: "c:/projects/Anaconda3-4.1.1-Windows-x86_64"
  SPHINXBUILD: "%PYTHON%/scripts/sphinx-build.exe"
  WHLPATH: "https://cntk.ai/PythonWheel/CPU-Only/cntk-2.5-cp35-cp35m-win_amd64.whl"

  github_access_token:
    secure: DpN0M7pZDocpyv+muc15qHDKz9lMJ7Zr34aMC0HtOdeVkbTERuKkxq4WHAd3S33v

init:
    - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

    - ps: (New-Object System.Net.WebClient).DownloadFile("https://repo.continuum.io/archive/Anaconda3-4.1.1-Windows-x86_64.exe", "c:\projects\Anaconda3-4.1.1-Windows-x86_64.exe")
    - start /wait c:\projects\Anaconda3-4.1.1-Windows-x86_64.exe /S /D=c:\projects\Anaconda3-4.1.1-Windows-x86_64

    - "%PYTHON%/python.exe -V"
    - "%PYTHON%/python.exe -m pip --version"

    # Install sphinx (1.5.5) and its extensions
    - "%PYTHON%/python.exe -m pip install sphinx==1.5.5"
    - "%PYTHON%/python.exe -m pip install sphinx-docfx-yaml"
    - "%PYTHON%/python.exe -m pip install sphinx_rtd_theme"
    - "%PYTHON%/python.exe -m pip show sphinx"
    - "%PYTHON%/python.exe -m pip show sphinx-docfx-yaml"

clone_script:
    - git config --global core.autocrlf true
    - git config core.autocrlf
    
    # get cntk 2.1 whl file
    # mkdir c:\projects\source
    # ps: (New-Object System.Net.WebClient).DownloadFile("https://cntk.ai/PythonWheel/CPU-Only/cntk-2.1-cp35-cp35m-win_amd64.whl", "c:\projects\source\cntk-2.1-cp35-cp35m-win_amd64.whl")
    
    # get cntk 
    - cd c:\projects
    - git clone -q --branch=%SOURCE_REPO_BRANCH% https://github.com/Microsoft/CNTK.git
 
    # get MicrosoftDocs/cognitive-toolkit-docs-python
    - cd c:\projects
    - git clone -q --branch=%PROCESS_REPO_BRANCH% https://github.com/MicrosoftDocs/cognitive-toolkit-docs-python.git

build: off

test: off

on_finish:
    - "%PYTHON%/python.exe -m pip install %WHLPATH%"
    - ps: Copy-Item c:/projects/cognitive-toolkit-docs-python/ci_scripts/conf.py -Destination c:/projects/cntk/bindings/python/doc/conf.py -force

    # generate rst files and build
    - echo %PATH%
    - set PATH=c:\projects\Anaconda3-4.1.1-Windows-x86_64;c:\projects\Anaconda3-4.1.1-Windows-x86_64\scripts;%PATH%
    - echo %PATH%
    - cd c:\projects\cntk\bindings\python\doc
    - call build.bat
    - "%SPHINXBUILD% . _build"

    # postprocess for toc.yml
    - ps: Copy-Item c:/projects/cognitive-toolkit-docs-python/ci_scripts/postprocess_toc_yml.py -Destination c:/projects/cntk/bindings/python/doc/postprocess_toc_yml.py -force
    - cd c:\projects\cntk\bindings\python\doc
    - dir _build\docfx_yaml
    - "%PYTHON%/python.exe postprocess_toc_yml.py"

    # remove old yml fils
    - ps: Remove-Item c:\projects\cognitive-toolkit-docs-python\docs-ref-autogen\$env:SOURCE_REPO_VERSION\* -recurse

    # copy yml fils generated
    - ps: Copy-Item -Path C:\projects\CNTK\bindings\python\doc\_build\docfx_yaml\* -Destination c:\projects\cognitive-toolkit-docs-python\docs-ref-autogen\$env:SOURCE_REPO_VERSION\ -recurse -force

    # upload yml to MicrosoftDocs/cognitive-toolkit-docs-python
    - git config --global credential.helper store
    - ps: ac "$env:USERPROFILE\.git-credentials" "https://$($env:github_access_token):x-oauth-basic@github.com`n"
    - cd c:\projects\cognitive-toolkit-docs-python
    - git status
    - git config --global user.name "VSC-Service-Account"
    - git config --global user.email "vscavu@microsoft.com"
    - git add . 
    - git commit -a -m "appveyor ci - update yml files" 
    - git push -u origin %PROCESS_REPO_BRANCH%:%PROCESS_REPO_BRANCH% -f

  
    # ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

    

  
